'use client'

import React, { useState } from 'react'
import { useRouter } from 'next/navigation'
import { useQuery } from '@tanstack/react-query'
import {
  FileCode,
  Copy,
  Download,
  Sparkles,
  Check,
  BookOpen,
  Code2,
  FileText,
  Sliders,
  Layers,
  ArrowRight
} from 'lucide-react'
import Navbar from '@/components/Navbar'

export default function LatexStudioPage() {
  const router = useRouter()
  const [topic, setTopic] = useState('Graph Retrieval-Augmented Generation & Large Language Models')
  const [template, setTemplate] = useState('neurips')
  const [includeTable, setIncludeTable] = useState(true)
  const [generating, setGenerating] = useState(false)
  const [copiedTex, setCopiedTex] = useState(false)
  const [copiedBib, setCopiedBib] = useState(false)

  // Fetch papers
  const { data: papers = [] } = useQuery({
    queryKey: ['papers-list'],
    queryFn: async () => {
      const res = await fetch('http://127.0.0.1:8000/api/v1/papers')
      if (!res.ok) return []
      return res.json()
    }
  })

  const [selectedPaperIds, setSelectedPaperIds] = useState<string[]>([])

  // Default sample LaTeX
  const [latexCode, setLatexCode] = useState<string>(`% ==========================================================================
% Systematic Literature Synthesis: Graph RAG & Representation Learning
% Generated by DeepGraph AI Academic Engine
% Template Style: NEURIPS
% ==========================================================================

\\section{Related Work and Empirical Synthesis}
\\label{sec:related_work}

Understanding the landscape of Graph RAG requires a structured taxonomy of existing methodologies.

\\paragraph{Attention Mechanisms and Sequence Transduction}
Vaswani et al. (2017) \\cite{vaswani2017attention} explored novel formulations in this domain. Specifically, their work replaces recurrent connections with multi-head self-attention mechanisms.

\\paragraph{Knowledge Graph Fusion in LLMs}
Chen et al. (2024) \\cite{chen2024graph} introduced explicit entity linking across unstructured text chunks to mitigate parametric hallucination.

\\begin{table*}[t]
\\centering
\\small
\\begin{tabular}{p{4.5cm}|p{2.2cm}|p{3.5cm}|p{3.5cm}}
\\hline
\\textbf{Publication / Reference} & \\textbf{Year / Venue} & \\textbf{Core Methodology} & \\textbf{Key Advantages} \\\\
\\hline
\\cite{vaswani2017attention} Attention Is All You Need & 2017 (NeurIPS) & Self-Attention & $O(1)$ sequential operations \\\\
\\cite{chen2024graph} Graph RAG Synthesis & 2024 (ICLR) & Hybrid Graph Fusion & Multi-hop factual precision \\\\
\\hline
\\end{tabular}
\\caption{Systematic taxonomy and comparison matrix for Graph RAG.}
\\label{tab:comparative_synthesis}
\\end{table*}

\\section{Methodological Synthesis and Open Challenges}
Across the examined corpus, several unresolved trade-offs emerge, particularly regarding computational scalability and semantic fidelity in large-scale multi-hop graphs.`)

  const [bibtexCode, setBibtexCode] = useState<string>(`@inproceedings{vaswani2017attention,
  author    = {Vaswani, Ashish and Shazeer, Noam and Parmar, Niki},
  title     = {Attention Is All You Need},
  booktitle = {Advances in Neural Information Processing Systems (NeurIPS)},
  year      = {2017}
}

@article{chen2024graph,
  author    = {Chen, Sophia and Rossi, Alexander},
  title     = {Graph Retrieval-Augmented Generation for Scientific Discovery},
  journal   = {International Conference on Learning Representations (ICLR)},
  year      = {2024}
}`)

  const handleGenerate = async () => {
    setGenerating(true)
    try {
      const activeIds = selectedPaperIds.length > 0 ? selectedPaperIds : papers.map((p: any) => p.id)
      const res = await fetch('http://127.0.0.1:8000/api/v1/export/latex', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          paper_ids: activeIds,
          topic: topic,
          template_style: template,
          include_comparison_table: includeTable
        })
      })
      if (res.ok) {
        const data = await res.json()
        setLatexCode(data.latex_code)
        setBibtexCode(data.bibtex_code)
      }
    } catch (e) {
      console.error(e)
    } finally {
      setGenerating(false)
    }
  }

  const copyToClipboard = (text: string, type: 'tex' | 'bib') => {
    navigator.clipboard.writeText(text)
    if (type === 'tex') {
      setCopiedTex(true)
      setTimeout(() => setCopiedTex(false), 2000)
    } else {
      setCopiedBib(true)
      setTimeout(() => setCopiedBib(false), 2000)
    }
  }

  const downloadFile = (content: string, filename: string) => {
    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="flex-1 flex flex-col min-h-screen">
      <Navbar
        title="LaTeX Paper Draft & Studio"
        subtitle="Generate compile-ready LaTeX literature reviews, comparison tables, and companion BibTeX bundles"
      />

      <div className="p-6 md:p-8 space-y-8 max-w-7xl mx-auto w-full">
        {/* Controls Configuration */}
        <div className="glass-panel rounded-3xl p-6 md:p-8 border border-border shadow-xl space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-12 gap-4">
            <div className="md:col-span-6 space-y-2">
              <label className="text-xs font-bold text-foreground">Survey Topic / Research Theme</label>
              <input
                type="text"
                value={topic}
                onChange={(e) => setTopic(e.target.value)}
                placeholder="e.g. Graph Retrieval-Augmented Generation"
                className="w-full bg-secondary/50 border border-border rounded-xl px-4 py-2.5 text-xs text-foreground focus:outline-none focus:border-brand-500"
              />
            </div>

            <div className="md:col-span-3 space-y-2">
              <label className="text-xs font-bold text-foreground">Conference Template</label>
              <select
                value={template}
                onChange={(e) => setTemplate(e.target.value)}
                className="w-full bg-secondary/50 border border-border rounded-xl px-4 py-2.5 text-xs text-foreground focus:outline-none focus:border-brand-500 font-mono"
              >
                <option value="neurips">NeurIPS (Camera Ready)</option>
                <option value="icml">ICML (Two Column)</option>
                <option value="ieee">IEEE Transactions</option>
                <option value="acm">ACM SIGKDD</option>
              </select>
            </div>

            <div className="md:col-span-3 flex items-end">
              <button
                onClick={handleGenerate}
                disabled={generating}
                className="w-full flex items-center justify-center space-x-2 px-6 py-2.5 rounded-xl bg-brand-500 hover:bg-brand-400 text-slate-950 font-bold text-xs transition-all shadow-md active:scale-95 disabled:opacity-50"
              >
                <Sparkles className="w-4 h-4" />
                <span>{generating ? 'Synthesizing...' : 'Generate LaTeX Draft'}</span>
              </button>
            </div>
          </div>
        </div>

        {/* Studio Code Workspace */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          {/* Main LaTeX Editor (8 cols) */}
          <div className="lg:col-span-8 glass-panel rounded-3xl p-6 border border-border space-y-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center space-x-2">
                <FileCode className="w-4 h-4 text-brand-400" />
                <span className="text-xs font-bold text-foreground font-mono">sections/related_work.tex</span>
              </div>

              <div className="flex items-center space-x-2">
                <button
                  onClick={() => copyToClipboard(latexCode, 'tex')}
                  className="flex items-center space-x-1 px-3 py-1.5 rounded-lg bg-secondary/80 hover:bg-secondary text-xs text-foreground border border-border font-mono transition-all"
                >
                  {copiedTex ? <Check className="w-3.5 h-3.5 text-teal-400" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copiedTex ? 'Copied' : 'Copy'}</span>
                </button>

                <button
                  onClick={() => downloadFile(latexCode, 'related_work.tex')}
                  className="flex items-center space-x-1 px-3 py-1.5 rounded-lg bg-brand-500/15 hover:bg-brand-500/25 text-xs text-brand-300 border border-brand-500/30 font-mono transition-all"
                >
                  <Download className="w-3.5 h-3.5" />
                  <span>Download .tex</span>
                </button>
              </div>
            </div>

            <textarea
              value={latexCode}
              onChange={(e) => setLatexCode(e.target.value)}
              rows={18}
              className="w-full bg-secondary/20 border border-border/80 rounded-2xl p-4 font-mono text-xs text-slate-200 focus:outline-none focus:border-brand-500 leading-relaxed resize-none"
            />
          </div>

          {/* BibTeX Sidebar (4 cols) */}
          <div className="lg:col-span-4 glass-panel rounded-3xl p-6 border border-border space-y-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center space-x-2">
                <BookOpen className="w-4 h-4 text-amber-400" />
                <span className="text-xs font-bold text-foreground font-mono">references.bib</span>
              </div>

              <div className="flex items-center space-x-2">
                <button
                  onClick={() => copyToClipboard(bibtexCode, 'bib')}
                  className="p-1.5 rounded-lg bg-secondary/80 hover:bg-secondary text-muted-foreground hover:text-foreground border border-border transition-all"
                  title="Copy BibTeX"
                >
                  {copiedBib ? <Check className="w-3.5 h-3.5 text-teal-400" /> : <Copy className="w-3.5 h-3.5" />}
                </button>

                <button
                  onClick={() => downloadFile(bibtexCode, 'references.bib')}
                  className="p-1.5 rounded-lg bg-secondary/80 hover:bg-secondary text-amber-300 border border-border transition-all"
                  title="Download .bib"
                >
                  <Download className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>

            <textarea
              value={bibtexCode}
              onChange={(e) => setBibtexCode(e.target.value)}
              rows={18}
              className="w-full bg-secondary/20 border border-border/80 rounded-2xl p-4 font-mono text-xs text-amber-200/90 focus:outline-none focus:border-amber-500 leading-relaxed resize-none"
            />
          </div>
        </div>
      </div>
    </div>
  )
}
